### ISSUE TITLE
State of AWSet implementation

### ISSUE THREAD

**Issue by farhadi** [derekkraan/delta_crdt_ex#12]
Hi Derek,

I was trying to write a distributed process group on top of your awesome DeltaCrdt package.
But it seems AWSet implementation is not ready yet.

I tried to add an element to an AWSet and it failed with this error: `function DeltaCrdt.AWSet.minimum_deltas/2 is undefined or private`

Also I can not read the state of an AWSet because `read` function is not implemented for AWSet.

Am I doing something wrong or it's not ready yet?
I thought maybe I can help If you give me some hints.

**Comment by derekkraan** [comment]
It is not implemented yet. There should be links to the papers in the
readme, that'll have details of how the read should work. You can implement
a passthrough minimum_delta for now if you just want to see it working
first.

Happy to answer any questions you might have while puzzling this out.

**Comment by derekkraan** [comment]
I'm going to close this for now. Feel free to continue the discussion below.
