### ISSUE TITLE
Some way to guarantee all deltas are shipped before termination

### ISSUE THREAD

**Issue by dazuma** [derekkraan/delta_crdt_ex#3]
I'm running into an issue (via Horde) where I make some changes to a CRDT and then stop the local copy. In some cases, the final changes are lost (i.e. don't get shipped out to the neighbors before the local copy stops). I'm wondering if there's a way to have a stronger guarantee.

I _think_ what I'm observing is this: Currently, `DeltaCrdt.CausalCrdt.terminate/2` calls `sync_interval_or_state_to_all/1` in an attempt to flush all changes. However, this ships deltas only to neighbors for which we aren't currently waiting for an outstanding ack. So it is possible for the changes not to get propagated if the CRDT is still waiting for acks.

Currently I am solving this downstream by inserting a delay between making my final change to the CRDT, and stopping the CRDT, enough time for acks to flush and the change to ship. However, it seems it would be cleaner if there was a way to "flush" all changes at the CRDT level.

**Comment by derekkraan** [comment]
I suspect you're on to something. One possibility is to clear the outstanding acks in the state struct before calling the sync function in the terminate callback. That would ensure that it actually sends all deltas from the last acks it has received.

Do you want to take a crack at a PR?

**Comment by dazuma** [comment]
I could. I wasn't clear, though, how to treat acks—whether they were critical for algorithm correctness or just a backpressure mechanism. (I haven't read the papers in detail...)

**Comment by derekkraan** [comment]
Sending the same delta twice is ok, skipping a delta is not ok, so we can
nuke the pending acks and still be fine. Acks are mostly a performance
optimization, you could send the entire state every time and still be
correct (but very slow). That is actually the backup mechanism for when we
have accidentally gc'd too aggressively and no longer have the deltas that
we need to send to a particular neighbour.
