### ISSUE TITLE
Using atom as a key possibly fail the VM

### ISSUE THREAD

**Issue by jung-hunsoo** [derekkraan/delta_crdt_ex#35]
I think it's better to add an issue here than `merkle_map` or `horde`, because the `merkle_map` is another kind of a map and `horde` leverages this library.

It looks the `DeltaCrdt` uses atom-type keys to propagates data, like `%{"CRDT" => "is magic!"}`. [src](https://github.com/derekkraan/delta_crdt_ex/blob/2d2f227f060f962c1796de0de90ed6f351681a87/lib/delta_crdt/causal_crdt.ex#L331)

That means whenever a mutation is occurred, a new atom can be created across the nodes which never garbage collected.

How about broadcasting data across the nodes to their own Agent to avoid bloating atom table?

**Comment by derekkraan** [comment]
Do you mean if you do something like `DeltaCrdt.mutate(crdt, :add, [:atom_key, "value"])`? Or something else?

**Comment by jung-hunsoo** [comment]
Both `mutate/4` and `mutate_async/3` calls `DeltaCrdt.CausalCrdt.handle_operation/2` which access `MerkleMap.put(mm, key, value)` when adding a data.

**Comment by derekkraan** [comment]
Yes, but this only applies when using `:atom_key` or similar, correct?

**Comment by jung-hunsoo** [comment]
OMG Sorry, I was totally confused. You're correct. It's good enough not to use atom type as a key.

**Comment by derekkraan** [comment]
:joy: no worries, thanks for reading the source code!

**Comment by jung-hunsoo** [comment]
Sorry for reopen. Though I don't think an inexperienced developer would use this lib or `horde`, how about adding a guide not to use atom type as a key? Any atoms either a key or a value will be replicated over the nodes but not eliminated.

**Comment by derekkraan** [comment]
I would accept a PR adding a warning about this to the docs or the readme, or both.

**Comment by derekkraan** [comment]
Also note: using an atom in the value will have the same result as using an atom in the key.
