### ISSUE TITLE
notify option is not supported yet

### ISSUE THREAD

**Issue by hissssst** [derekkraan/delta_crdt_ex#50]
I can provide the PR

**Comment by zachdaniel** [comment]
This would be great to see :)

**Comment by derekkraan** [comment]
Hi, can you explain what the notify option would do?

**Comment by zachdaniel** [comment]
The option is documented here: https://hexdocs.pm/delta_crdt/DeltaCrdt.html#start_link/2

But isn't supported.

**Comment by derekkraan** [comment]
Ah yes, this option was supported in the past but was removed in favour of `on_diffs`, which you can see documented here: https://hexdocs.pm/delta_crdt/DeltaCrdt.html#t:crdt_option/0

You can make `on_diffs` do the same job as a `notify` would have done.

I would accept a PR to clean up the documentation.
